export const DEGEN_MARKETS_ABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string", name: "id", type: "string" },
      {
        indexed: false,
        internalType: "address",
        name: "acceptor",
        type: "address",
      },
    ],
    name: "BetAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string", name: "id", type: "string" },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "creationTimestamp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "ticker",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "metric",
        type: "string",
      },
      { indexed: false, internalType: "bool", name: "isBetOnUp", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "expirationTimestamp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "currency",
        type: "address",
      },
    ],
    name: "BetCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string", name: "id", type: "string" },
      {
        indexed: false,
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    name: "BetSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "string", name: "id", type: "string" },
    ],
    name: "BetWithdrawn",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [{ internalType: "string", name: "_betId", type: "string" }],
    name: "acceptBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "acceptanceTimeLimit",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "betIdToBet",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "address", name: "creator", type: "address" },
      { internalType: "uint256", name: "creationTimestamp", type: "uint256" },
      { internalType: "string", name: "ticker", type: "string" },
      { internalType: "string", name: "metric", type: "string" },
      { internalType: "bool", name: "isBetOnUp", type: "bool" },
      { internalType: "uint256", name: "expirationTimestamp", type: "uint256" },
      { internalType: "address", name: "acceptor", type: "address" },
      { internalType: "address", name: "winner", type: "address" },
      { internalType: "uint256", name: "value", type: "uint256" },
      { internalType: "address", name: "currency", type: "address" },
      { internalType: "bool", name: "isWithdrawn", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_id", type: "string" },
      { internalType: "uint256", name: "_duration", type: "uint256" },
      { internalType: "string", name: "_ticker", type: "string" },
      { internalType: "string", name: "_metric", type: "string" },
      { internalType: "bool", name: "_isBetOnUp", type: "bool" },
      { internalType: "uint256", name: "_value", type: "uint256" },
      { internalType: "address", name: "_currency", type: "address" },
    ],
    name: "createBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "maximumBetDuration",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minimumBetDuration",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_acceptanceTimeLimit",
        type: "uint256",
      },
    ],
    name: "setAcceptanceTimeLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_maximumBetDuration", type: "uint256" },
    ],
    name: "setMaximumBetDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_minimumBetDuration", type: "uint256" },
    ],
    name: "setMinimumBetDuration",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_betId", type: "string" },
      { internalType: "address", name: "_winner", type: "address" },
    ],
    name: "settleBet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_betId", type: "string" }],
    name: "withdrawBet",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
