name: Deploy to Prod & Dev

on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Linting with ESLint
        run: npm run lint

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, production] # this run two environment parallel
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Remove .vercel directory
        run: rm -rf .vercel

      - name: Create env file
        run: echo "NEXT_PUBLIC_ENV=${{ matrix.environment }}" > .env

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g vercel

          # Deploy based on environment
          if [ "${{ matrix.environment }}" == "production" ]; then
            DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
          else
            DEPLOYMENT_URL=$(vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')
            # Set alias for development
            vercel alias set $(echo $DEPLOYMENT_URL | sed 's|https\?://||') dev.degenmarkets.com --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID || {
              echo "Failed to set alias. Check domain permissions."
              exit 1
            }
          fi

          echo "Deployment successful!"
          echo "Access your application at: $DEPLOYMENT_URL"
